require 'rubygems'
require 'openssl'
require 'digest/md5'
require 'base64'
require 'net/http'
require 'net/https'
require 'uri'
require 'cgi'
require 'rexml/document'
require 'json'
require 'date'

require_relative '../../lib/tripit'
TRIPIT_KEY = 'INSERTYOURKEYHERE'
TRIPIT_SECRET = 'INSERTYOURSECRETHERE'
